INFO:__main__:使用 8 个GPU进行训练
INFO:__main__:需要加载视觉backbone: /home/Qwen2.5-VL-3B-Instruct
INFO:__main__:请确保提供正确的CLIP或其他视觉模型路径
INFO:__main__:布局模型参数数量: 53,288,966
INFO:__main__:视觉模型参数数量: 393,984
INFO:__main__:总参数数量: 53,682,950
INFO:__main__:train 数据集包含 800 个样本
INFO:__main__:val 数据集包含 200 个样本
INFO:__main__:训练器初始化完成，使用设备: cuda
INFO:__main__:开始训练模式
INFO:__main__:开始训练，共 100 个epoch
#########backbone_name######### clip
#########load visual backbone okk ##########
#########init models okk ##########
Epoch 1/100:   0%|          | 0/25 [00:00<?, ?it/s]Epoch 1/100:   0%|          | 0/25 [00:16<?, ?it/s]
#########train step##########
Traceback (most recent call last):
  File "/home/LayoutMaster/train.py", line 1099, in <module>
    main()
  File "/home/LayoutMaster/train.py", line 1054, in main
    trainer.train()
  File "/home/LayoutMaster/train.py", line 793, in train
    loss_dict = self.train_step(batch)
  File "/home/LayoutMaster/train.py", line 539, in train_step
    visual_features = self.visual_extractor(images)  # [B, N, visual_dim]
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/data_parallel.py", line 185, in forward
    outputs = self.parallel_apply(replicas, inputs, module_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/data_parallel.py", line 200, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/parallel_apply.py", line 108, in parallel_apply
    output.reraise()
  File "/usr/local/lib/python3.10/dist-packages/torch/_utils.py", line 705, in reraise
    raise exception
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/parallel_apply.py", line 83, in _worker
    output = module(*input, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/LayoutMaster/models.py", line 342, in forward
    raise RuntimeError("Backbone not set. Call set_backbone() first.")
RuntimeError: Backbone not set. Call set_backbone() first.

